config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  # devise_scope :user do
  #   delete 'sign_out',
  #   :to => 'devise/sessions#destroy', :as => :destroy_user_session
  #   end
  get "users/:id" => "users#show", as: :user
  get "users/:id/applications" => "users#applications", as: :user_applications
  resources :industries, only: [:show, :edit, :update, :destroy]
  resources :categories, only: [:show, :edit, :update, :destroy]
  resources :companies do
    resources :jobs, except: [:index]
    collection { post :import }
    get :autocomplete_company_name, on: :collection
    post :claim
  end
  resources :applications, only: [:create, :destroy]
  resources :interests, only: [:index, :create, :destroy]
end

app/models/company.rb
class Company < ActiveRecord::Base
	require "csv"
	require 'open-uri'

	mount_uploader :logo, LogoUploader
	has_many :jobs
	has_many :companyindustries
	has_many :industries, through: :companyindustries
	accepts_nested_attributes_for :industries
	has_many :admins, dependent: :destroy
	has_many :users, through: :admins
	has_many :interests, foreign_key: "followed_id", dependent: :destroy
	has_many :followers, through: :interests
	searchable do
		text :name, :boost => 5
		text :industries do
			industries.map { |industry| industry.name }
		end
		text :mission
		text :description
	end

	def country_name
	    country = ISO3166::Country[location]
	    country.translations[I18n.locale.to_s] || country.name
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			company_hash = {:id => row["id"], :mission => row["mission"], :description => row["description"],
											:remote_logo_url => row["logo"], :name => row["name"], :location => row["location"],
											:employees => row["employees"], :url => row["url"]}
			company = Company.find_by(name: company_hash[:name]) || new
			company.attributes = company_hash.slice(:mission, :description, :remote_logo_url, :name, :location,
																								:employees, :url)
			company.save!
		end
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  autocomplete :company, :name
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def import
    @company = Company.new
    begin
      Company.import(params[:file])
      redirect_to companies_path, notice: "Companies successfully imported"
    rescue
      redirect_to companies_path, notice: "Invalid CSV"
    end
  end

  def index
    @search = Company.search do
      fulltext params[:search]
    end
    @companies = @search.results
  end

  def claim
    @company = Company.find(params[:company_id])
    @user = current_user
    @user.claim(@company)
    redirect_to @company
  end

  def show
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        format.html { redirect_to companies_path, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:mission, :description, :name, :logo, :location, :url, :employees, :making, :industry_ids => [])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<h3>Mass upload / edit (.csv)</h3>
<%= form_tag import_companies_path, multipart: true, method: :post, action: :import do %>
  <%= file_field_tag :file %>
  <br>
  <%= submit_tag :import%>
<% end %>

<%= simple_form_for @company, html: { multipart: true } do |f| %>
<%= f.error_notification %>
    <br>
    <%= f.input :name, label: "Company name", input_html: { class: "small"} %>
    <%= f.input :mission %>
    <%= f.input :url, input_html: {class: "medium"}, label: "Homepage URL"%>
    <%= f.input :description, as: :text, input_html: { class: "textbox"}%>
    <%= f.input :making, as: :text, input_html: { class: "textbox"}, label: "What we're making"%>
    <%= f.input :industry_ids, as: :check_boxes, collection: Industry.all, label: "Industries", value: :id %>
    <%= f.input :location, as: :country, label: "HQ location", input_html: { class: "small"} %>
    <%= f.input :employees, collection: ["1-10", "11-50", "51-200", "200+"], input_html: { class: "small"} %>
    <%= f.input :logo %>
    <%= f.submit %>
<% end %>

app/views/companies/_minijobs.html.erb
<div class="minijobs-wrapper">
  <p class = "mini">
    <%= link_to "#{company.jobs.first.title}", company_job_path(company, company.jobs.first.id), class: "silent" %>
        | up to
        <%= number_to_human(company.jobs.first.salarymin,
                            precision: 2,
                            separator: '.',
                            significant: true,
                            units: { thousand: "k"})%>
            | <%= company.jobs.first.country_name %> </p>

  <p class = "mini">
    <%= link_to "#{company.jobs.second.title}", company_job_path(company, company.jobs.second.id) %>
        | up to
        <%= number_to_human(company.jobs.second.salarymin,
                            precision: 2,
                            separator: '.',
                            significant: true,
                            units: { thousand: "k"})%>
            | <%= company.jobs.second.country_name %> </p>
</div>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<%= render 'layouts/searchbar'%>
<% @companies.each do |company| %>
    <div class="media plate">
        <div class="media-left">
                <div class="media-object">
                    <%= image_tag(company.logo.thumb) if company.logo?%>
                </div>
        </div>
        <div class="media-body">
            <div class="media-heading">
                <h4><strong><%= link_to "#{company.name}", company_path(company), class: "silent" %></strong></h4>
            </div>
            <p>Mission: <em><%= company.mission%></em></p>
            <span class = "plate-font">Industries:</span>
              <% company.industries.each do |i| %>
                <span class = "nodec tag inline silent"><%= link_to "#{i.name}", industry_path(i), class: "silent"%></span>
              <% end %>
            <% if company.jobs.count >= 2 %>
                <%= render "minijobs", company: company %>
            <% end %>

            <div class="details silent">
                <hr id = "dark">
                <h4 class = "silent">About us:</h4>
                <p class = "silent"><%= company.description %></p>
            </div>

            <% if user_signed_in? && current_user.role == "admin" %>
                 <p><%= link_to "Edit '#{company.name}'", edit_company_path(company) %> |
                 <%= link_to "Delete '#{company.name}'", company, method: :delete, data: { confirm: 'Are you sure?' } %></p>
            <% end %>
        </div>
    </div>
<% end %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<div class="plate company-page">

	<div class="container jumbotron">
		<div class="logo">
			<%= image_tag(@company.logo.square) if @company.logo?%>
		</div>
		<h1><%= @company.name %></h1>
		<p>Mission: <%= @company.mission %></p>
	</div>
	<div class="row">
		<div class="col-md-8 philosophy">

			<h2>About us</h2>
				<p><%= @company.description %></p>
			<br>
			<h2>What we're making</h2>
				<p><%= @company.making %></p>
		</div>
		<div class="col-md-4">
			<h4>Industry:</h4>
			<p><% @company.industries.each do |i| %>
	                <li class = "nodec tag inline"><%= link_to "#{i.name}", industry_path(i)%></li>
	            <% end %>
	        </p>
			<h4>Headquarters:</h4>
			<p><%= @company.country_name %></p>
			<h4>Employees:</h4>
			<p><%= @company.employees %></p>
			<h4>Website:</h4>
			<p><%= link_to "#{@company.url}", @company.url %></p>
			<% if user_signed_in? %>
				<div id="follow_form">
					<% if current_user.following?(@company) %>
						<%= render 'interests/unfollow' %>
					<% else %>
						<%= render 'interests/follow' %>
					<% end %>
				</div>
				<br>
					<%= link_to "Claim #{@company.name}", company_claim_path(@company), method: :post if @company.users.exclude?(current_user) %>
					<%= link_to "Edit #{@company.name}", edit_company_path(@company) if @company.users.include?(current_user) || current_user.role == "admin" %>
			<% end %>
		</div>
	</div>
	<div class="row">
	  <div class="col-md-12">
	    <h2>Vacancies:</h2>
	      <% if (@company.jobs.count == 0) %>
	        <p>No vacancies at this time. Please check <%= @company.name %> link (ADD LINK HERE) for more details</p>
	      <% else %>
					<%= render "shared/jobtable", company: @company %>
				<% end %>
		</div>
	</div>
	<% if (user_signed_in? && current_user.role == "admin") || @company.users.include?(current_user) %>
		<%= link_to "Add a new job", new_company_job_path(@company) %> |
	<% end %>
</div>