config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  # devise_scope :user do
  #   delete 'sign_out',
  #   :to => 'devise/sessions#destroy', :as => :destroy_user_session
  #   end
  get "users/:id" => "users#show", as: :user
  get "users/:id/applications" => "users#applications", as: :user_applications
  resources :industries, only: [:show, :edit, :update, :destroy]
  resources :categories, only: [:show, :edit, :update, :destroy]
  resources :companies do
    resources :jobs, except: [:index]
    collection { post :import }
    get :autocomplete_company_name, on: :collection
    post :claim
  end
  resources :applications, only: [:create, :destroy]
  resources :interests, only: [:index, :create, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role == "admin"
        can :manage, :all
    else
        can :read, :all
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  belongs_to :user
	belongs_to :company
end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :applicant, class_name: "User"
  belongs_to :job
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :jobcategories
	has_many :jobs, through: :jobcategories
end

app/models/company.rb
class Company < ActiveRecord::Base
	require "csv"
	require 'open-uri'

	mount_uploader :logo, LogoUploader
	has_many :jobs
	has_many :companyindustries
	has_many :industries, through: :companyindustries
	accepts_nested_attributes_for :industries
	has_many :admins, dependent: :destroy
	has_many :users, through: :admins
	has_many :interests, foreign_key: "followed_id", dependent: :destroy
	has_many :followers, through: :interests
	searchable do
		text :name, :boost => 5
		text :industries do
			industries.map { |industry| industry.name }
		end
		text :mission
		text :description
	end

	def country_name
	    country = ISO3166::Country[location]
	    country.translations[I18n.locale.to_s] || country.name
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			company_hash = {:id => row["id"], :mission => row["mission"], :description => row["description"],
											:remote_logo_url => row["logo"], :name => row["name"], :location => row["location"],
											:employees => row["employees"], :url => row["url"]}
			company = Company.find_by(name: company_hash[:name]) || new
			company.attributes = company_hash.slice(:mission, :description, :remote_logo_url, :name, :location,
																								:employees, :url)
			company.save!
		end
	end
end

app/models/companyindustry.rb
class Companyindustry < ActiveRecord::Base
	belongs_to :company
	belongs_to :industry
end

app/models/industry.rb
class Industry < ActiveRecord::Base
	has_many :companyindustries
	has_many :companies, through: :companyindustries
end

app/models/interest.rb
class Interest < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "Company"
end

app/models/job.rb
class Job < ActiveRecord::Base
	validates :title, presence: true
	validates :salarymin, presence: true, numericality: { greater_than: 1, less_than: :salarymax}
	validates :salarymax, presence: true, numericality: { greater_than: 1, less_than: 999000}
	belongs_to :company
	has_many :jobcategories
	has_many :categories, through: :jobcategories
	has_many :jobreqs
	has_many :reqs, through: :jobreqs
	has_many :applications
	has_many :applicants, through: :applications

	def country_name
	    country = ISO3166::Country[location]
	    country.translations[I18n.locale.to_s] || country.name
	end

end

app/models/jobcategory.rb
class Jobcategory < ActiveRecord::Base
	belongs_to :job
	belongs_to :category
end

app/models/jobreq.rb
class Jobreq < ActiveRecord::Base
  belongs_to :job
  belongs_to :req
end

app/models/req.rb
class Req < ActiveRecord::Base
  has_many :jobreqs
  has_many :jobs, through: :jobreqs
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :userskills
  has_many :users, through: :userskills
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  ROLES = %w[admin user]
  has_many :userskills
  has_many :skills, through: :userskills
  accepts_nested_attributes_for :skills
  has_many :admins, dependent: :destroy
  has_many :applications, foreign_key: "applicant_id", dependent: :destroy
  has_many :job_applications, through: :applications, source: :job
  has_many :companies, through: :admins
  has_many :interests, foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :interests, source: :followed
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.firstname = auth.info.name
      user.image = auth.info.image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def apply(job)
    applications.create(job_id: job.id)
  end

  def unapply(job)
    applications.find_by(job_id: job.id).destroy
  end

  def applied?(job)
    job_applications.include?(job)
  end

  def follow(company)
  	interests.create(followed_id: company.id)
  end

  def unfollow(company)
  	interests.find_by(followed_id: company.id).destroy
  end

  def following?(company)
  	following.include?(company)
  end

  def claim(company)
    admins.create(company_id: company.id)
  end

end

app/models/userskill.rb
class Userskill < ActiveRecord::Base
  belongs_to :user
  belongs_to :skill
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<div class="nav navbar-default white navbar-fixed-top">
	<div class="container-fluid">
		<a href="/" class="navbar-brand">Missions</a>
		<ul class = "nav navbar-nav">
			<!-- Logged in -->
			<% if user_signed_in? %>
				<li class = "profile-pic"><%= link_to image_tag(current_user.image.nav), user_path(current_user)%></li>
				<li><%= link_to "Logged in as #{current_user.email}", user_path(current_user)%></li>
				<li><%= link_to "Log out", destroy_user_session_path, method: :delete%></li>
			<% else %>

			<!-- Logged out -->
				<li><%= link_to "Log in", new_user_session_path %></li>
				<li><%= link_to "Sign up", new_user_registration_path %></li>
				<li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
			<%end%>

			<!-- Admin options  -->
			<% if user_signed_in? && current_user.role == "admin" %>
			    <li><%= link_to 'Add a new Company', new_company_path %></li>
			<% end %>

		</ul>

	</div>
</div>

app/views/layouts/_profilelinks.html.erb
<div class="plate">
	<div class = "sidebar-button">
		<span class = "glyphicon glyphicon-cog">
			<%= link_to "Edit profile", edit_user_registration_path(current_user)%>
		</span>
		
	</div>
</div>
<br>

app/views/layouts/_searchbar.html.erb
<div class="plate">
	<%= form_tag companies_path, method: :get do %>
		<%= text_field_tag :search, params[:search], class: "search-query searchbar",
											placeholder: "United States",
											type: "search",
											data: {autocomplete: autocomplete_company_name_companies_path} %>
		<%= submit_tag "Search", name: nil, class: "hidden", id: "search-submit" %></p>
	<% end %>
</div>

app/views/layouts/_shortcuts.html.erb
<p class = "sidebar-mini-header">Shortcuts</p>
<div class="plate">
		<p class = "sidebar-button"><%= link_to "Browse all", companies_path %></p>
	<% if user_signed_in? %>
		<p class = "sidebar-button border-top"><%= link_to "Following", interests_path %></p>
		<p class="sidebar-button border-top">
			<%= link_to "My applications", user_applications_path(current_user) %>
		</p>
	<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobs</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "autocomplete-rails.js" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>



  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid wrapper">
		<% if notice %>
			<div class="notice-wrapper">
				<p class="notice"><%= notice %></p>
			</div>
		<% elsif alert %>
			<div class="notice-wrapper error">
				<p class="alert"><%= alert %></p>
			</div>
		<% end %>
		<%= render 'layouts/navigation' %>
			<div class="container nav-clear">
				<div class="row">
					<div class="col-md-3 sidebar">
						<%= render 'layouts/profilelinks' if user_signed_in? %>
						<%= render 'layouts/shortcuts' %>
					</div>

					<div class="col-md-9">
						<%= yield %>
					</div>
				</div>
			</div>
		<%= render 'layouts/footer'	%>
	</div>
</body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobs</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "autocomplete-rails.js" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid wrapper">
		<%= render 'layouts/navigation' %>
        <%= yield %>
	</div>
</body>
<%= render 'layouts/footer'	%>
</html>

app/views/shared/_jobtable.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Role</th>
      <th>Location</th>
      <th>Type</th>
      <th>Category</th>
      <th>Salary</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% company.jobs.each do |j| %>
      <tr>
        <td><%= link_to "#{j.title}", company_job_path(company, j) %></td>
        <td><%= j.country_name %></td>
        <td><%= j.jobtype %></td>
        <td><% j.categories.each do |c| %>
              <%= link_to "#{c.name}", category_path(c) %>
            <% end %> </p></td>
        <td> <%= number_to_human(j.salarymin, precision: 2,
                      separator: '.',
                      significant: true, units: { thousand: "k"}) %> to
              <%= number_to_human(j.salarymax, precision: 2,
                            separator: '.',
                            significant: true, units: { thousand: "k"}) %> </td>
        <% if (user_signed_in? && current_user.role == "admin") || company.users.include?(current_user) %>
                   <td class = "pad">
                    <%= link_to "Edit job", edit_company_job_path(company, j) %>
                   </td>
              <% end %>
      </tr> <!-- close jobs row -->
    <% end %> <!-- end jobs loop -->
  </tbody>
</table> <!-- close table -->